/// <reference types="next/image-types/global" />

// WHY THIS FILE EXISTS, WHEN next-env.d.ts ALREADY SAYS THE SAME LINE.
//
// `next-env.d.ts` is GITIGNORED (.gitignore:16). It is generated by `next dev`
// and `next build`, so it is present on any machine that has ever run one and
// absent on a fresh checkout. It carries the reference that declares image
// modules — the thing that gives `import poster from "./x.png"` a type.
//
// CI runs `typecheck` BEFORE `build`, on a fresh checkout. So the first static
// image import in this repository (app/_media, MKT-02B) typechecked locally and
// failed in CI with TS2307 "Cannot find module … or its corresponding type
// declarations" — passing for every developer and failing for everyone else.
// Reproduced by deleting next-env.d.ts and re-running tsc.
//
// This file is the committed half of that declaration. It references Next's own
// image types rather than hand-rolling `declare module "*.png"`: a hand-rolled
// duplicate would have to guess StaticImageData's shape and would then disagree
// with Next's whenever the real file IS present.
//
// `next-env.d.ts` also references `./.next/types/routes.d.ts`, which genuinely
// does not exist before a build — which is why the fix is this narrow reference
// and not committing next-env.d.ts itself.
