import { useId } from "react";
import { cx, CONTROL_MIN_TOUCH, FOCUS_RING } from "@/components/ui/control-base";
import { TreatmentAreaPicker } from "@/components/waitlist/treatment-area-picker";
import {
  AVAILABILITY_PREFERENCES,
  AVAILABILITY_PREFERENCE_HELP,
  AVAILABILITY_PREFERENCE_LABEL,
  PROFILE_EMAIL_MAX,
  PROFILE_FIRST_NAME_MAX,
  PROFILE_LAST_NAME_MAX,
  PROFILE_MOBILE_MAX,
  type AvailabilityPreference,
  type JoinProfileDraft,
  type ProfileFieldErrors,
} from "@/lib/waitlist/join-profile";
import {
  SMS_OPERATIONAL_CONSENT_DECLINED_NOTE,
  SMS_OPERATIONAL_CONSENT_FIELD,
  SMS_OPERATIONAL_CONSENT_LABEL,
} from "@/lib/waitlist/prospect-sms-consent";
import {
  AVAILABILITY_HELP,
  AVAILABILITY_LEGEND,
  MOBILE_CANDIDATE_NOTE,
  MOBILE_ON_FILE_NOTE,
} from "@/lib/waitlist/join-copy";
import type { TreatmentAreaId } from "@/lib/waitlist/treatment-area-catalog";

// ===========================================================================
// WAIT-04A — THE PROFILE FIELD SET
// ===========================================================================
//
// ONE FIELD SET, TWO SURFACES. The new-join form and the legacy completion
// panel ask the SAME questions — they differ only in their heading, their
// framing and what happens on submit. Rendering them from one component is what
// makes "complete" mean the same thing on both; two hand-maintained copies
// would drift the moment a field is added, and the completion path — the one
// nobody looks at — would be the copy that rots.
//
// EVERY FIELD IS LABELLED, AND THE LABEL IS THE TARGET. `htmlFor`/`id` pairs
// throughout, generated by `useId` so two instances on one page cannot collide.
// Errors are `role="alert"` and joined to their input by `aria-describedby`,
// so a screen reader hears the problem WITH the field rather than as loose text
// somewhere on the page.
//
// AVAILABILITY IS A RADIO GROUP WITH NO PRE-SELECTION. Three real radios in a
// fieldset — arrow keys move within the group, the legend is announced on
// entry, and exactly one answer is possible. Nothing is checked initially,
// which is the entire fake-completeness rule expressed in markup: a default
// would have the form answer on the person's behalf and look identical
// afterwards.
//
// SMS CONSENT IS UNTICKED, ALONE, AND NOT REQUIRED. It sits after the submit
// -relevant fields, is never bundled with anything else, and its own help text
// says declining is fine. `smsOperationalConsent` is not in
// `REQUIRED_PROFILE_FIELDS`, so nothing here can gate on it.
//
// NO FREE TEXT BEYOND THE FOUR IDENTITY FIELDS. No notes, no urgency, no
// "anything else we should know". There is no such prop, so a caller cannot
// pass one in.
// ===========================================================================

const CARD_BORDER = "#E5E2D9";
const INK = "#0A0A0A";
const MUTED = "#6B6B6B";

function TextField({
  id,
  label,
  value,
  onChange,
  error,
  type,
  autoComplete,
  inputMode,
  maxLength,
  disabled,
  testId,
}: {
  id: string;
  label: string;
  value: string;
  onChange: (next: string) => void;
  error?: string;
  type: string;
  autoComplete: string;
  inputMode?: "text" | "email" | "tel";
  maxLength: number;
  disabled: boolean;
  testId: string;
}) {
  const errorId = `${id}-error`;
  return (
    <div className="flex w-full flex-col gap-1">
      <label htmlFor={id} className="text-[12px] uppercase tracking-[0.1em]" style={{ color: MUTED }}>
        {label} <span aria-hidden="true">*</span>
      </label>
      <input
        id={id}
        data-testid={testId}
        type={type}
        required
        autoComplete={autoComplete}
        inputMode={inputMode}
        maxLength={maxLength}
        value={value}
        disabled={disabled}
        onChange={(e) => onChange(e.target.value)}
        aria-invalid={error ? true : undefined}
        aria-describedby={error ? errorId : undefined}
        className={cx(
          "w-full max-w-full bg-transparent py-2 text-[16px] outline-none",
          FOCUS_RING,
        )}
        style={{ borderBottom: `1px solid ${error ? "#DC2626" : INK}`, color: INK }}
      />
      {error && (
        <span id={errorId} role="alert" className="text-[13px] text-red-600">
          {error}
        </span>
      )}
    </div>
  );
}

export function ProfileFields({
  draft,
  errors,
  onChange,
  disabled = false,
  emailLocked = false,
  mobileLocked = false,
  showMobileCandidateNote = false,
}: {
  draft: JoinProfileDraft;
  errors: ProfileFieldErrors;
  onChange: (next: JoinProfileDraft) => void;
  disabled?: boolean;
  /**
   * Render the email as READ-ONLY text instead of an input.
   *
   * Set on the completion surface, where it is a security property rather than
   * a convenience. That surface is reached by possession of a link, and the
   * address on the entry is where every future invitation is sent — so an
   * editable email field would let whoever holds the link redirect the studio's
   * next offer to an address of their choosing. Every legacy entry already has
   * an email (that is the one field they all have), so nothing is lost by
   * fixing it: changing it is a support conversation with the studio, not a
   * form field on a bearer-reachable page.
   */
  emailLocked?: boolean;
  /**
   * Render the mobile as READ-ONLY text instead of an input.
   *
   * Set on the completion surface WHENEVER THE ENTRY ALREADY HOLDS A NUMBER,
   * for the same reason as `emailLocked` and against a sharper threat: the
   * mobile is where SMS goes, so a bearer link able to replace it would point
   * the studio's texts at whoever holds the link — and a consent tick in the
   * same submission would arrive looking like agreement for the new number.
   *
   * A legacy entry with NO number leaves this false: supplying one is the whole
   * point of that visit. What it supplies is a CANDIDATE, never a verified
   * destination — see `showMobileCandidateNote`.
   */
  mobileLocked?: boolean;
  /**
   * Say out loud that a newly typed number is not yet usable.
   *
   * Product-visible because the alternative is implying we will text a number
   * we have not confirmed. `prospectMayReceiveSms` refuses to send to an
   * unverified number, so without this note the copy and the behaviour disagree.
   */
  showMobileCandidateNote?: boolean;
}) {
  const firstId = useId();
  const lastId = useId();
  const emailId = useId();
  const mobileId = useId();
  const availabilityHelpId = useId();
  const availabilityErrorId = useId();
  const consentId = useId();
  const consentNoteId = useId();

  return (
    <div className="flex w-full max-w-full flex-col gap-5" data-testid="waitlist-profile-fields">
      {/* Two fields, not one. A single "Name" box cannot be addressed properly
          later, and splitting one afterwards is the guess this product refuses
          to make. */}
      <div className="flex w-full flex-col gap-5 sm:flex-row sm:gap-4">
        <TextField
          id={firstId}
          testId="waitlist-field-first-name"
          label="First name"
          type="text"
          autoComplete="given-name"
          maxLength={PROFILE_FIRST_NAME_MAX}
          value={draft.firstName}
          error={errors.firstName}
          disabled={disabled}
          onChange={(firstName) => onChange({ ...draft, firstName })}
        />
        <TextField
          id={lastId}
          testId="waitlist-field-last-name"
          label="Last name"
          type="text"
          autoComplete="family-name"
          maxLength={PROFILE_LAST_NAME_MAX}
          value={draft.lastName}
          error={errors.lastName}
          disabled={disabled}
          onChange={(lastName) => onChange({ ...draft, lastName })}
        />
      </div>

      {emailLocked ? (
        <div className="flex w-full flex-col gap-1" data-testid="waitlist-field-email-locked">
          <span className="text-[12px] uppercase tracking-[0.1em]" style={{ color: MUTED }}>
            Email
          </span>
          {/* Plain text, not a disabled input: a greyed-out box invites someone
              to try to enable it, and a disabled input is still a form control
              a forged post could carry a value for. There is no email control
              on this surface at all. */}
          <p className="py-2 text-[16px]" style={{ color: INK }}>
            {draft.email}
          </p>
          <p className="text-[13px] leading-[1.6]" style={{ color: MUTED }}>
            Contact the studio if this address needs to change.
          </p>
        </div>
      ) : (
        <TextField
          id={emailId}
          testId="waitlist-field-email"
          label="Email"
          type="email"
          autoComplete="email"
          inputMode="email"
          maxLength={PROFILE_EMAIL_MAX}
          value={draft.email}
          error={errors.email}
          disabled={disabled}
          onChange={(email) => onChange({ ...draft, email })}
        />
      )}

      {mobileLocked ? (
        <div className="flex w-full flex-col gap-1" data-testid="waitlist-field-mobile-locked">
          <span className="text-[12px] uppercase tracking-[0.1em]" style={{ color: MUTED }}>
            Mobile
          </span>
          {/* Plain text, not a disabled input. A disabled control is still a
              control a forged post could carry a value for; there is no mobile
              control on this surface at all when a number is on file. */}
          <p className="py-2 text-[16px]" style={{ color: INK }}>
            {draft.mobile}
          </p>
          <p className="text-[13px] leading-[1.6]" style={{ color: MUTED }}>
            {MOBILE_ON_FILE_NOTE}
          </p>
        </div>
      ) : (
        <div className="flex w-full flex-col gap-1">
          <TextField
            id={mobileId}
            testId="waitlist-field-mobile"
            label="Mobile"
            type="tel"
            autoComplete="tel"
            inputMode="tel"
            maxLength={PROFILE_MOBILE_MAX}
            value={draft.mobile}
            error={errors.mobile}
            disabled={disabled}
            onChange={(mobile) => onChange({ ...draft, mobile })}
          />
          {showMobileCandidateNote && (
            <p
              className="text-[13px] leading-[1.6]"
              style={{ color: MUTED }}
              data-testid="waitlist-mobile-candidate-note"
            >
              {MOBILE_CANDIDATE_NOTE}
            </p>
          )}
        </div>
      )}

      <TreatmentAreaPicker
        selected={draft.treatmentAreaIds}
        error={errors.treatmentAreaIds ?? null}
        disabled={disabled}
        onToggle={(id: TreatmentAreaId, next: boolean) => {
          const kept = draft.treatmentAreaIds.filter((existing) => existing !== id);
          onChange({
            ...draft,
            treatmentAreaIds: next ? [...kept, id] : kept,
          });
        }}
      />

      <fieldset
        className="flex w-full max-w-full flex-col gap-2 border-0 p-0"
        data-testid="waitlist-availability"
        aria-describedby={
          errors.availabilityPreference
            ? `${availabilityHelpId} ${availabilityErrorId}`
            : availabilityHelpId
        }
        aria-invalid={errors.availabilityPreference ? true : undefined}
        disabled={disabled}
      >
        <legend className="text-[12px] uppercase tracking-[0.1em]" style={{ color: MUTED }}>
          {AVAILABILITY_LEGEND} <span aria-hidden="true">*</span>
        </legend>
        <p
          id={availabilityHelpId}
          className="text-[13px] leading-[1.6]"
          style={{ color: MUTED }}
        >
          {AVAILABILITY_HELP}
        </p>
        {AVAILABILITY_PREFERENCES.map((preference: AvailabilityPreference) => (
          <label
            key={preference}
            data-testid={`waitlist-availability-${preference}`}
            data-selected={draft.availabilityPreference === preference ? "true" : "false"}
            className={cx(
              CONTROL_MIN_TOUCH,
              "w-full cursor-pointer justify-start gap-3 py-1 text-[15px]",
              disabled && "cursor-not-allowed opacity-60",
            )}
            style={{ color: INK }}
          >
            <input
              type="radio"
              name="availability_preference"
              value={preference}
              // NOT defaulted. An unanswered group has no checked radio.
              checked={draft.availabilityPreference === preference}
              disabled={disabled}
              onChange={() => onChange({ ...draft, availabilityPreference: preference })}
              className={cx("h-5 w-5 shrink-0 accent-black", FOCUS_RING)}
            />
            <span>
              {AVAILABILITY_PREFERENCE_LABEL[preference]}{" "}
              <span style={{ color: MUTED }}>
                {AVAILABILITY_PREFERENCE_HELP[preference]}
              </span>
            </span>
          </label>
        ))}
        {errors.availabilityPreference && (
          <span
            id={availabilityErrorId}
            role="alert"
            data-testid="waitlist-availability-error"
            className="text-[13px] text-red-600"
          >
            {errors.availabilityPreference}
          </span>
        )}
      </fieldset>

      {/* Its own bordered block so it reads as a separate question rather than
          the tail of the availability group. Optional, and says so. */}
      <div
        className="flex flex-col gap-1 pt-1"
        style={{ borderTop: `1px solid ${CARD_BORDER}` }}
        data-testid="waitlist-sms-consent"
      >
        <label
          htmlFor={consentId}
          className={cx(
            CONTROL_MIN_TOUCH,
            "w-full cursor-pointer items-start justify-start gap-3 py-2 text-[14px] leading-[1.6]",
            disabled && "cursor-not-allowed opacity-60",
          )}
          style={{ color: INK }}
        >
          <input
            id={consentId}
            data-testid="waitlist-field-sms-consent"
            type="checkbox"
            name={SMS_OPERATIONAL_CONSENT_FIELD}
            // Opt-in. Never defaulted true, and never derived from the mobile
            // field having a value in it.
            checked={draft.smsOperationalConsent}
            disabled={disabled}
            onChange={(e) =>
              onChange({ ...draft, smsOperationalConsent: e.target.checked })
            }
            aria-describedby={consentNoteId}
            className={cx("mt-[2px] h-5 w-5 shrink-0 accent-black", FOCUS_RING)}
          />
          <span>{SMS_OPERATIONAL_CONSENT_LABEL}</span>
        </label>
        <p
          id={consentNoteId}
          className="text-[13px] leading-[1.6]"
          style={{ color: MUTED }}
        >
          {SMS_OPERATIONAL_CONSENT_DECLINED_NOTE}
        </p>
      </div>
    </div>
  );
}
