-- ---------------------------------------------------------------------------
-- 0168 — L18 Phase 4: narrow write commands for public.treatment_images
--
-- WHAT THIS REPLACES
-- ===========================================================================
-- Verified runtime writer census (statement-chain accurate, reads excluded —
-- 77 read-only chains across the L18 tables were measured and NOT counted):
--
--   treatment_images (3), all in app/(app)/clients/[id]/images/actions.ts
--     uploadTreatmentImageAction        INSERT  :199
--     updateTreatmentImageNoteAction    UPDATE  :333
--     archiveTreatmentImageAction       UPDATE  :368
--
-- AFTER this migration and its application half, EVERY L18 table reports zero
-- direct runtime writers: sessions 0, session_blocks 0, session_block_areas 0,
-- electrolysis_entries 0, laser_entries 0, treatment_images 0.
--
-- STORAGE AND POSTGRES ARE NOT ONE TRANSACTION
-- ===========================================================================
-- The upload writes a storage object through the SERVICE-ROLE storage client
-- and then records metadata through the AUTHENTICATED database client. Those
-- are two different planes and cannot share a transaction, so the application
-- MUST keep its compensating cleanup: if metadata creation fails it removes the
-- uploaded object, and if that removal also fails it raises a CRITICAL
-- orphaned-object alert. This migration does not change that, and nothing here
-- should be read as making the upload atomic — it is not.
--
-- These commands deliberately cannot upload, sign or delete a storage object.
-- They only write the metadata row.
--
-- WHAT IS PRESERVED, DELIBERATELY
-- ===========================================================================
-- * SECURITY DEFINER bypasses RLS, so every command re-establishes the tenant
--   boundary itself: the studio and the acting practitioner are DERIVED from
--   auth.uid(), never accepted from the caller, and every statement is scoped
--   by studio_id.
-- * All three treatment_images triggers still fire for DEFINER writes —
--   treatment_images_set_updated_at, treatment_images_enforce_integrity (0093,
--   which freezes the identity columns) and treatment_images_guard_finalized —
--   as do the bucket-fixed and path-shape CHECK constraints.
-- * The note command enforces the 1000-character limit as a BACKSTOP; the
--   application keeps its own validation and its exact wording.
-- * Archive is SOFT only. No command deletes a row or a storage object.
-- * Zero-row outcomes are reported as a distinct, non-revealing result so the
--   application can keep saying "Treatment photo not found." without leaking
--   whether another client's image exists.
--
-- L18 REMAINS OPEN after this migration. Direct authenticated table DML is NOT
-- revoked here. Revocation is a separate, final L18 migration — this phase only
-- removes the last application writer.
--
-- Own transaction + armed lock_timeout: `supabase db push` does not wrap a
-- migration file in a transaction, so a bare SET LOCAL emits 25P01 and never
-- arms (the 0159 lesson).
--
-- Migration max 0167 -> 0168.
-- ---------------------------------------------------------------------------

begin;

set local lock_timeout = '5s';

-- ===========================================================================
-- INTERNAL HELPER — resolve the acting practitioner and their studio.
--
-- The actor is ALWAYS auth.uid(). current_user is deliberately not consulted:
-- inside a SECURITY DEFINER function it is the owner, not the practitioner.
-- ===========================================================================
create or replace function public.treatment_image_actor()
returns table (studio_id uuid, practitioner_id uuid)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_studio uuid;
  v_pract  uuid;
begin
  if auth.uid() is null then
    raise exception 'An authenticated practitioner is required.'
      using errcode = 'check_violation';
  end if;

  select p.studio_id, p.id into v_studio, v_pract
    from public.practitioners p
   where p.user_id = auth.uid()
     and p.active = true
   limit 1;

  if v_pract is null then
    raise exception 'No active practitioner found for the signed-in user.'
      using errcode = 'check_violation';
  end if;

  return query select v_studio, v_pract;
end;
$$;

-- ===========================================================================
-- COMMAND 1 — record treatment-image metadata for an object the caller has
-- ALREADY uploaded. Replaces uploadTreatmentImageAction's INSERT.
--
-- The image id and storage path are generated by the application before the
-- storage upload, so they are accepted here — but the path is re-derived and
-- checked against the actor's own studio, the asserted client and that id, so a
-- forged path cannot point at another tenant's prefix.
-- ===========================================================================
create or replace function public.create_treatment_image_metadata(
  p_id                uuid,
  p_client_id         uuid,
  p_session_id        uuid,
  p_session_block_id  uuid,
  p_storage_bucket    text,
  p_storage_path      text,
  p_original_filename text,
  p_content_type      text,
  p_size_bytes        bigint
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_studio      uuid;
  v_pract       uuid;
  v_session     uuid := p_session_id;
  v_block_sess  uuid;
  v_expected    text;
begin
  select a.studio_id, a.practitioner_id into v_studio, v_pract
    from public.treatment_image_actor() a;

  if p_id is null or p_client_id is null then
    raise exception 'Could not save the image.' using errcode = 'check_violation';
  end if;

  -- The client must belong to the actor's studio.
  perform 1 from public.clients c
    where c.id = p_client_id and c.studio_id = v_studio;
  if not found then
    raise exception 'That client is not available.' using errcode = 'check_violation';
  end if;

  -- A block implies its session: derive the session FROM the block, and refuse
  -- a submitted session id that disagrees with it.
  if p_session_block_id is not null then
    select b.session_id into v_block_sess
      from public.session_blocks b
      join public.sessions s on s.id = b.session_id
     where b.id = p_session_block_id
       and b.studio_id = v_studio
       and s.studio_id = v_studio
       and s.client_id = p_client_id;

    if v_block_sess is null then
      raise exception 'That treatment area is not available for this client.'
        using errcode = 'check_violation';
    end if;
    if p_session_id is not null and p_session_id <> v_block_sess then
      raise exception 'That treatment area is not available for this client.'
        using errcode = 'check_violation';
    end if;
    v_session := v_block_sess;
  elsif p_session_id is not null then
    perform 1 from public.sessions s
      where s.id = p_session_id
        and s.studio_id = v_studio
        and s.client_id = p_client_id;
    if not found then
      raise exception 'That session is not available for this client.'
        using errcode = 'check_violation';
    end if;
  end if;

  -- Bucket is fixed, and the path must be exactly the studio/client/id prefix
  -- this actor is allowed to write. The 0093 CHECKs enforce the same shape;
  -- checking here refuses a forged path with a clean message instead of a
  -- constraint error.
  if p_storage_bucket is distinct from 'treatment-images' then
    raise exception 'Could not save the image.' using errcode = 'check_violation';
  end if;
  v_expected := v_studio::text || '/' || p_client_id::text || '/' || p_id::text || '.';
  if p_storage_path is null or position(v_expected in p_storage_path) <> 1 then
    raise exception 'Could not save the image.' using errcode = 'check_violation';
  end if;

  insert into public.treatment_images (
    id, studio_id, client_id, session_id, session_block_id,
    storage_bucket, storage_path, original_filename, content_type, size_bytes,
    uploaded_by
  ) values (
    p_id, v_studio, p_client_id, v_session, p_session_block_id,
    p_storage_bucket, p_storage_path, p_original_filename, p_content_type,
    p_size_bytes,
    -- DERIVED, never accepted from the caller.
    v_pract
  );

  return p_id;
end;
$$;

-- ===========================================================================
-- COMMAND 2 — add / edit / clear the practitioner note. Replaces
-- updateTreatmentImageNoteAction's UPDATE.
--
-- Scoped by id + studio + client + not-already-archived, exactly as before, and
-- returns NULL when no row matched so the application can keep its generic
-- "Treatment photo not found." without revealing another client's image.
-- ===========================================================================
create or replace function public.set_treatment_image_note(
  p_image_id  uuid,
  p_client_id uuid,
  p_note      text
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_studio uuid;
  v_pract  uuid;
  v_note   text;
  v_id     uuid;
begin
  select a.studio_id, a.practitioner_id into v_studio, v_pract
    from public.treatment_image_actor() a;

  -- Trim, then whitespace-only becomes NULL — the application's own rule,
  -- repeated here so the stored value cannot depend on the caller trimming.
  v_note := nullif(btrim(coalesce(p_note, '')), '');

  -- BACKSTOP only: the application validates first and owns the wording.
  if v_note is not null and length(v_note) > 1000 then
    raise exception 'Note is too long.' using errcode = 'check_violation';
  end if;

  update public.treatment_images t
     set practitioner_note = v_note
   where t.id = p_image_id
     and t.studio_id = v_studio
     and t.client_id = p_client_id
     and t.deleted_at is null
  returning t.id into v_id;

  -- NULL = no row matched (missing, wrong client, or already archived).
  return v_id;
end;
$$;

-- ===========================================================================
-- COMMAND 3 — soft-archive a treatment photo. Replaces
-- archiveTreatmentImageAction's UPDATE.
--
-- SOFT only: `deleted_at` is stamped by the DATABASE and `deleted_by` is
-- DERIVED from auth.uid(). No storage object is touched. Returns NULL when no
-- row matched, so an already-archived or wrong-client id is a generic
-- "not found" rather than a silent success.
-- ===========================================================================
create or replace function public.archive_treatment_image(
  p_image_id  uuid,
  p_client_id uuid
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_studio uuid;
  v_pract  uuid;
  v_id     uuid;
begin
  select a.studio_id, a.practitioner_id into v_studio, v_pract
    from public.treatment_image_actor() a;

  update public.treatment_images t
     set deleted_at = now(),
         deleted_by = v_pract
   where t.id = p_image_id
     and t.studio_id = v_studio
     and t.client_id = p_client_id
     and t.deleted_at is null
  returning t.id into v_id;

  return v_id;
end;
$$;

-- ===========================================================================
-- PRIVILEGES
--
-- Supabase's ALTER DEFAULT PRIVILEGES grants EXECUTE to anon, authenticated AND
-- service_role at function-create time. An authenticated-only command must
-- revoke from all three explicitly, by name, plus PUBLIC. 0129 revoked only
-- PUBLIC and leaked `anon`; 0164 revoked PUBLIC+anon and left `service_role`.
-- Literal, per-signature statements so the grant guard can see them.
--
-- The internal helper is revoked from authenticated too and never granted back.
-- ===========================================================================

revoke execute on function public.treatment_image_actor() from public;
revoke execute on function public.treatment_image_actor() from anon;
revoke execute on function public.treatment_image_actor() from service_role;
revoke execute on function public.treatment_image_actor() from authenticated;

revoke execute on function public.create_treatment_image_metadata(uuid, uuid, uuid, uuid, text, text, text, text, bigint) from public;
revoke execute on function public.create_treatment_image_metadata(uuid, uuid, uuid, uuid, text, text, text, text, bigint) from anon;
revoke execute on function public.create_treatment_image_metadata(uuid, uuid, uuid, uuid, text, text, text, text, bigint) from service_role;
revoke execute on function public.create_treatment_image_metadata(uuid, uuid, uuid, uuid, text, text, text, text, bigint) from authenticated;

revoke execute on function public.set_treatment_image_note(uuid, uuid, text) from public;
revoke execute on function public.set_treatment_image_note(uuid, uuid, text) from anon;
revoke execute on function public.set_treatment_image_note(uuid, uuid, text) from service_role;
revoke execute on function public.set_treatment_image_note(uuid, uuid, text) from authenticated;

revoke execute on function public.archive_treatment_image(uuid, uuid) from public;
revoke execute on function public.archive_treatment_image(uuid, uuid) from anon;
revoke execute on function public.archive_treatment_image(uuid, uuid) from service_role;
revoke execute on function public.archive_treatment_image(uuid, uuid) from authenticated;

grant execute on function public.create_treatment_image_metadata(uuid, uuid, uuid, uuid, text, text, text, text, bigint) to authenticated;
grant execute on function public.set_treatment_image_note(uuid, uuid, text) to authenticated;
grant execute on function public.archive_treatment_image(uuid, uuid) to authenticated;

commit;
