-- ===========================================================================
-- WAIT-ADMIT-01 — ADMISSION SCHEMA (DESIGN PROTOTYPE — NOT A MIGRATION)
-- ===========================================================================
--
-- NO MIGRATION NUMBER IS CLAIMED. Outside supabase/migrations/, no NNNN_
-- prefix, so `npm run migration:state` does not see it: repo max 0191, next
-- free 0192, pending (none). 0192 is NOT reserved by this file.
--
-- ---------------------------------------------------------------------------
-- REVISION — A PRIVILEGE MODEL RECORDED HERE WAS DISPROVED
-- ---------------------------------------------------------------------------
--
-- An earlier version of this document proposed:
--
--     alter table public.studios add column waitlist_ranking_policy jsonb;
--
-- THAT IS WITHDRAWN. It repeated, in full, the defect WAIT-03B/B1 had already
-- found and corrected for its own allowance column. Re-proved mechanically
-- against production (project alhhybgqdmcdyzpybykj) before rewriting this file:
--
--   1. pg_default_acl carries, for tables in public, from BOTH the `postgres`
--      and `supabase_admin` grantors:
--          anon=arwdDxtm | authenticated=arwdDxtm | service_role=arwdDxtm
--      arwdDxtm is INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES,
--      TRIGGER, MAINTAIN. So EVERY new table in public is created with full DML
--      already granted to the browser roles. Nothing in a migration has to do
--      it, and grepping the migrations for `grant ... on studios` finds
--      nothing — because no statement ever granted it.
--
--   2. Consequently public.studios today grants UPDATE to anon AND to
--      authenticated across ALL 47 of its columns
--      (information_schema.role_column_grants). A 48th column inherits that on
--      creation.
--
--   3. The grant CANNOT be narrowed per column. `REVOKE UPDATE (col)` against a
--      table-level grant succeeds and changes nothing — B1's proof observed
--      exactly this ("silently left anon/authenticated able to write it").
--      RLS cannot substitute: an RLS policy authorises a ROW, never a column.
--      So on studios there is NO mechanism, grant or policy, able to say
--      "owners may edit the studio, but ranking policy needs a command".
--
--   4. What actually protects studios today is one predicate in one policy:
--          "studios: owners update"  TO authenticated
--          USING is_studio_owner(id)  WITH CHECK is_studio_owner(id)
--      and is_studio_owner requires role='owner' AND active=true. So an
--      ordinary member CANNOT write studios today. The defect is not a live
--      member-write hole; it is that the design could not STRUCTURALLY prevent
--      one, and any future permissive UPDATE policy on studios admitting
--      members for any unrelated reason would admit them to admission policy
--      in the same statement.
--
-- THE CORRECTION, and it is B1's: an independently owned table, which starts
-- from the same armed defaults and therefore MUST strip them explicitly. The
-- canonical template is migration 0185 (new_client_waitlist_entries):
--
--     revoke all on <table> from public, anon, authenticated, service_role;
--     grant select on <table> to authenticated;
--
-- Verified in production: new_client_waitlist_entries grants authenticated
-- SELECT and nothing else; new_client_waitlist_invitations — which holds a
-- token hash — grants anon, authenticated and service_role NOTHING AT ALL.
-- Those two postures are the precedents used below, chosen by whether the
-- table holds a secret.
--
-- ---------------------------------------------------------------------------
-- THE TWO AUTHORITIES, SEPARATED
-- ---------------------------------------------------------------------------
--
--   PROSPECT PREFERENCE   the prospect's own answer about when they can attend.
--                         Updated by the prospect (token) or by a practitioner
--                         relaying a phone call. Never an admission decision.
--
--   ADMISSION POLICY      how the studio ranks and how many it invites.
--                         OWNER-ONLY. Never prospect-reachable, never
--                         member-writable.
--
-- They are separate TABLES with separate commands, so no single write path
-- spans them and a bug in one cannot reach the other.
-- ===========================================================================


-- ===========================================================================
-- UNIT A — ENTRY-ORIGIN PROVENANCE  (columns on the existing entries table)
-- ===========================================================================
--
-- SAFE TO PUT HERE, and the reason is specific rather than assumed:
-- new_client_waitlist_entries grants `authenticated` SELECT ONLY and `anon`
-- nothing, so there is no browser write path for a new column to inherit. The
-- studios hazard does not reach this table.
--
-- FORWARD RULE: never take a TABLE-level UPDATE grant on this table. While it
-- holds none, a future column can still be made browser-writable with a
-- COLUMN-level grant (column GRANT works; only column REVOKE against a table
-- grant does not). Once a table-level grant exists that door cannot be shut.
--
-- All three are written ONCE, at creation, by the commands in Unit E.
--
--   ~ source CHECK widened  -> ('public_booking','practitioner','legacy_import')
--   + created_by_practitioner_id  uuid NULL, composite (id, studio_id) FK to
--     practitioners, ON DELETE RESTRICT
--   + joined_at_provenance  text NOT NULL DEFAULT 'form'
--                           CHECK IN ('form','operator_supplied','unknown')
--
--   CHECK  source='public_booking' <-> created_by IS NULL       (both ways)
--   CHECK  source='public_booking' <-> provenance='form'        (both ways)
--
-- The DEFAULT 'form' fabricates nothing: the CHECK being replaced is
-- `source = 'public_booking'` single-valued, which PROVES every existing row
-- arrived through the public form.
--
-- joined_at stays NOT NULL. Under provenance 'unknown' it is a QUEUE ANCHOR
-- ONLY. The honest residual risk: it looks like a real date to any reader that
-- ignores the provenance column. lib/waitlist never reads one without the
-- other — waitIsMeasurable=false, the waiting-time factor returns UNKNOWN,
-- daysWaiting is null rather than 0.
--
-- `name` REMAINS NOT NULL. name_provenance stays PROPOSED-ONLY (see Unit F).


-- ===========================================================================
-- UNIT B — PROSPECT PREFERENCE   (new table, prospect-owned)
-- ===========================================================================
--
--   public.new_client_waitlist_entry_preferences
--     entry_id      uuid PRIMARY KEY
--     studio_id     uuid NOT NULL
--     preference    text NOT NULL  CHECK IN ('weekdays','weekends','both')
--     stated_at     timestamptz NOT NULL      -- value last set or CHANGED
--     confirmed_at  timestamptz NOT NULL      -- last AFFIRMED, changed or not
--                   CHECK (confirmed_at >= stated_at)
--     source        text NOT NULL
--                   CHECK IN ('public_form','practitioner','prospect_link')
--     recorded_by_practitioner_id  uuid NULL
--                   CHECK source='practitioner' <-> recorded_by NOT NULL
--     FK (entry_id, studio_id) -> new_client_waitlist_entries (id, studio_id)
--        ON DELETE CASCADE
--     FK (recorded_by_practitioner_id, studio_id) -> practitioners (id, studio_id)
--
-- WHY A TABLE AND NOT COLUMNS, stated plainly: NOT because of the grant hazard,
-- which does not reach the entries table. Two other reasons:
--
--   * "NOT STATED" BECOMES THE ABSENCE OF A ROW. Every column is then NOT NULL
--     and the four-column completeness CHECK the column design needed
--     disappears. Not-stated becomes unforgeable rather than CHECK-enforced.
--
--   * WRITE CONTAINMENT. A command that writes preferences can be scoped to a
--     table holding nothing else, so a bug in it cannot touch status,
--     claimed_at, invited_at or any lifecycle evidence. On the entry row an
--     over-broad UPDATE could.
--
-- TWO TIMESTAMPS, NOT ONE. Collapsing them forces a choice of which truth to
-- lose: move one column on re-confirmation and the history of the value is
-- destroyed; do not move it and the preference ages out while the person is
-- actively telling you it still holds. Age is measured from confirmed_at.
-- Implemented and tested in lib/waitlist/confirmation.ts (applyConfirmation).
--
-- GRANTS — 0185 posture (no secret in this table):
--     revoke all on public.new_client_waitlist_entry_preferences
--       from public, anon, authenticated, service_role;
--     grant select on public.new_client_waitlist_entry_preferences
--       to authenticated;
--   RLS ON. One policy: FOR SELECT TO authenticated USING is_studio_owner(studio_id).
--   No insert/update/delete policy. No grant to anon. No grant to service_role
--   — SECURITY DEFINER commands execute as their owner and need no table
--   privilege, which is what makes the write path unreachable from a session.


-- ===========================================================================
-- UNIT C — STUDIO ADMISSION POLICY   (new table, OWNER-owned)
-- ===========================================================================
--
-- THIS IS THE UNIT THAT REPLACES THE WITHDRAWN studios COLUMN.
--
--   public.studio_waitlist_admission_policy
--     studio_id                  uuid PRIMARY KEY
--                                REFERENCES studios(id) ON DELETE CASCADE
--     ranking_policy             jsonb NOT NULL   -- weights, preferredDayClass,
--                                                 -- unknownPolicy, cap
--     invite_batch_default       integer NOT NULL CHECK (>= 0)
--     invite_batch_max           integer NOT NULL CHECK (>= invite_batch_default)
--     updated_at                 timestamptz NOT NULL DEFAULT now()
--     updated_by_practitioner_id uuid NOT NULL
--     FK (updated_by_practitioner_id, studio_id) -> practitioners (id, studio_id)
--
-- NO ROW = FIFO ordering and no configured batch = today's exact behaviour, so
-- landing this changes nothing for any studio. Same "absence is the default"
-- shape B1 uses for studio_waitlist_admission_rounds.
--
-- DISTINCT FROM B1's studio_waitlist_admission_rounds, deliberately: that table
-- holds THIS ROUND's allowance and is transient; this one holds standing
-- configuration. If B1 lands, B1's allowance remains authoritative for what may
-- actually issue, and invite_batch_* are defaults and bounds for the
-- recommendation, never permission to admit.
--
-- ranking_policy is jsonb as STORAGE ONLY. Every parse rule already exists and
-- is tested in lib/waitlist/policy.ts, where ABSENT means FIFO and MALFORMED
-- means refuse — kept distinct so a corrupt document cannot silently reorder a
-- queue while the operator believes their policy is running.
--
-- GRANTS — 0185 posture:
--     revoke all on public.studio_waitlist_admission_policy
--       from public, anon, authenticated, service_role;
--     grant select on public.studio_waitlist_admission_policy to authenticated;
--   RLS ON. One policy: FOR SELECT TO authenticated USING is_studio_owner(studio_id).
--   READ is owner-only as well as write: a member has no business reading how
--   the studio ranks its queue, and is_studio_member would have been the
--   broader, lazier predicate.
--   NO write policy and NO write grant to ANY role, so the ONLY way to change
--   admission policy is the Unit E command — which re-derives owner role in
--   the database from (studio_id, auth user id) and cannot be reached from a
--   browser session at all.


-- ===========================================================================
-- UNIT D — PREFERENCE-UPDATE GRANTS   (new table, secret-bearing)
-- ===========================================================================
--
--   public.new_client_waitlist_preference_grants
--     id, studio_id, entry_id, token_hash, issued_at, expires_at,
--     issued_by_practitioner_id, redeemed_at, revoked_at
--     CHECK (expires_at > issued_at)
--     CHECK (redeemed_at is null or revoked_at is null)
--     composite same-studio FKs to entries and practitioners
--     UNIQUE (token_hash)
--     UNIQUE (entry_id) WHERE redeemed_at is null and revoked_at is null
--        -- one live grant per entry: two outstanding links means two people
--        -- can answer the same question and the later answer silently wins.
--
-- SEPARATE FROM new_client_waitlist_invitations because that table's
-- cycle-evidence CHECK requires claimed_at + claimed_by + invited_at for status
-- 'invited', so issuing one drags a waiting prospect through claim -> invite.
-- Asking which days suit someone is not an offer of an appointment, and reusing
-- the invitation would consume an admission allowance to ask a question.
--
-- GRANTS — INVITATIONS posture, because this table holds a token hash:
--     revoke all on public.new_client_waitlist_preference_grants
--       from public, anon, authenticated, service_role;
--     -- and NO grant is issued to any role.
--   RLS ON with an owner SELECT policy for defence in depth, even though no
--   role holds SELECT to exercise it. Operator reads go through a SECURITY
--   DEFINER function that never returns token_hash.


-- ===========================================================================
-- UNIT E — COMMANDS   (contracts only; bodies belong with the slot)
-- ===========================================================================
--
-- Every one: SECURITY DEFINER, and written as LITERAL statements (never a
-- DO-block with format()) because the grant guards read them textually:
--
--     revoke execute on function <sig> from public;
--     revoke execute on function <sig> from anon;
--     revoke execute on function <sig> from authenticated;
--     revoke execute on function <sig> from service_role;
--     grant  execute on function <sig> to service_role;
--
-- All four revokes by name — ALTER DEFAULT PRIVILEGES arms anon, authenticated
-- AND service_role at function-create time. Missed for anon in 0129 and for
-- service_role in 0164; tests/security/clinical-rpc-grant-guard.test.ts exists
-- because of it.
--
-- PROSPECT-PREFERENCE AUTHORITY (minimum required, and no more)
--   set_waitlist_entry_availability(studio, entry, actor_user, preference)
--       Practitioner relaying a phone call or walk-in. Writes UNIT B ONLY.
--       Authorises through the existing new_client_waitlist_resolve_owner.
--   redeem_waitlist_preference_grant(token, preference)
--       The prospect's own path. NO session: authority is the hashed token,
--       validated INSIDE the mutating transaction. Writes UNIT B ONLY, and can
--       set only `preference` — never status, never any lifecycle column.
--       Failure is indistinguishable across wrong / expired / redeemed /
--       revoked / removed-entry, so it cannot be used to probe membership.
--   issue_waitlist_preference_grant / revoke_waitlist_preference_grant
--       Owner-authorised. Returns the raw token once; stores only its hash.
--
-- ADMISSION-POLICY AUTHORITY (owner-only)
--   set_studio_waitlist_admission_policy(studio, actor_user, ranking_policy,
--                                        invite_batch_default, invite_batch_max)
--       The ONLY write path to Unit C. Re-derives owner role in the database
--       via new_client_waitlist_resolve_owner; the browser supplies neither a
--       role nor a studio_id it did not prove membership of.
--   claim_new_client_waitlist_entries_ordered(studio, actor_user, entry_ids[])
--       Ranked counterpart to the existing FIFO claim. Preserves the lease, the
--       FOR UPDATE SKIP LOCKED contention rule and the single decision instant
--       — none of which may regress.
--
-- MANUAL / LEGACY ENTRY CREATION
--   create_practitioner_waitlist_entry(studio, actor_user, name, email, phone,
--                                      availability_preference)
--   import_legacy_waitlist_entry(studio, actor_user, name, email, phone,
--                                joined_at, joined_at_provenance)
--       joined_at and its provenance MUST be passed explicitly. There is no
--       defaulting path, which is what stops now() erasing a real wait.


-- ===========================================================================
-- UNIT F — name_provenance   PROPOSED ONLY, NOT IMPLEMENTED
-- ===========================================================================
--
-- `name` remains NOT NULL with its existing length CHECK. Nothing reads a name
-- provenance and no DDL for it appears in this document.
--
-- REDUNDANT with `source` for the source-level distinction. Needed for exactly
-- one thing source cannot express: within a legacy import, a name the operator
-- KNOWS from correspondence versus one GUESSED from an email local part — both
-- are 'legacy_import'. That case is today closed by REFUSAL, not schema:
-- planLegacyWaitlistImport returns a nameless row as needs_decision and there is
-- deliberately no allowUnknownName counterpart to allowUnknownJoinedAt. The
-- column becomes necessary only if that refusal is relaxed at volume. The
-- vocabulary is already defined and tested (lib/waitlist/provenance.ts).


-- ===========================================================================
-- REQUIRED PROOFS BEFORE THIS IS BELIEVED (fresh local reset, never production)
-- ===========================================================================
-- Grants, per new table, using the has_table_privilege pattern already
-- established in tests/db/new-client-waitlist-entries.db.test.ts:
--   G1  anon holds NOTHING on all three new tables (select included)
--   G2  authenticated holds SELECT and nothing else on Units B and C
--   G3  authenticated holds NOTHING on Unit D (it carries token_hash)
--   G4  service_role holds NOTHING on any of the three
--   G5  anon and authenticated hold no EXECUTE on any Unit E command
-- Authority:
--   A1  a MEMBER (role<>'owner') calling set_studio_waitlist_admission_policy
--       is refused, and no row changes
--   A2  an owner of studio X cannot write policy for studio Y
--   A3  a member cannot SELECT Unit C at all
--   A4  redeem_waitlist_preference_grant cannot alter status/claimed_at/
--       invited_at — assert the whole entry row is byte-identical after it
--   A5  an expired, revoked, redeemed and unknown token are indistinguishable
--       to the caller
-- Data:
--   D1  every pre-existing entry: source='public_booking', provenance='form'
--   D2  source='practitioner' without created_by                    -> FAILS
--   D3  source='legacy_import' with provenance='form'               -> FAILS
--   D4  confirmed_at < stated_at                                    -> FAILS
--   D5  availability source='prospect_link' WITH a recorder          -> FAILS
--   D6  two live grants for one entry                               -> FAILS
--   D7  lib/waitlist projects real rows unchanged — still FIFO until a studio
--       actually collects preferences
