"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { getCurrentPractitionerWithStudio } from "@/lib/supabase/queries";
import { isPractitionerColor } from "@/lib/practitioner-colors";
import {
  generateCalendarFeedToken,
  hashCalendarFeedToken,
} from "@/lib/calendar-feed/token";

function trimmedOrThrow(
  value: FormDataEntryValue | null,
  label: string,
): string {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw new Error(`${label} is required.`);
  }
  return value.trim();
}

export async function updateOwnProfileAction(formData: FormData): Promise<void> {
  const { studio } = await getCurrentPractitionerWithStudio();
  const displayName = trimmedOrThrow(
    formData.get("display_name"),
    "Your name",
  );

  // 0178: governed own-preference command. NO practitioner id crosses the
  // boundary — the DATABASE binds the actor to auth.uid() and the explicit
  // studio, so there is nothing here to forge.
  const supabase = await createClient();
  const { data: updatedId, error } = await supabase.rpc(
    "update_own_practitioner_profile",
    { p_studio_id: studio.id, p_display_name: displayName, p_color: null },
  );
  if (error) {
    throw new Error(`Failed to save your name: ${error.message}`);
  }
  // NULL = no ACTIVE membership in that studio. Before 0178 the owner-only RLS
  // policy made this a SILENT zero-row write for every non-owner; reporting
  // success for a write that did not happen is the exact bug being closed.
  if (!updatedId) {
    throw new Error("Failed to save your name: no active membership.");
  }

  revalidatePath("/settings/profile");
  revalidatePath("/settings/studio");
  revalidatePath("/settings/team");
  revalidatePath("/dashboard");
}

export async function updatePractitionerColorAction(
  formData: FormData,
): Promise<void> {
  const { studio } = await getCurrentPractitionerWithStudio();
  const token = formData.get("color");
  if (!isPractitionerColor(token)) {
    throw new Error("Pick a color from the palette.");
  }

  const supabase = await createClient();
  const { data: updatedId, error } = await supabase.rpc(
    "update_own_practitioner_profile",
    { p_studio_id: studio.id, p_display_name: null, p_color: token },
  );
  if (error) {
    throw new Error(`Failed to save your color: ${error.message}`);
  }
  if (!updatedId) {
    throw new Error("Failed to save your color: no active membership.");
  }

  revalidatePath("/settings/profile");
  revalidatePath("/calendar");
}

// ---------------------------------------------------------------------------
// Calendar feed token (migration 0046 + PR #182 / migration 0079)
// ---------------------------------------------------------------------------
// Generates or rotates the per-practitioner secret used as the path
// segment for the private iCal subscription feed at
// /calendar-feed/<token>.ics. Acts as both "create" and "rotate":
// the row's previous token is overwritten by an UPDATE, so any
// subscribed Google Calendar polling the old URL immediately starts
// receiving 404.
//
// Token entropy: 32 random bytes -> base64url (~43 chars). Generated
// with Node's crypto.randomBytes (CSPRNG) via the shared
// generateCalendarFeedToken helper.
//
// PR #182 phase 1 hashing model:
//   * The runtime feed route looks up by calendar_feed_token_hash
//     (SHA-256 hex) instead of the raw token (migration 0079).
//   * Rotation writes BOTH the raw column AND the hash column for
//     this phase. The raw column is what the existing settings UI
//     reads on page render to display the URL; nulling it here would
//     break the URL display on the deploy boundary. Phase 2 (a
//     separate PR) refactors the UI to display the URL only at
//     rotation time and then nulls the raw column.
//   * Clear nulls BOTH columns so the partial unique on either side
//     does not retain a stale value.
//
// The action returns the new raw token to the caller; the Settings
// page derives the full URL on the client. The hash is server-only
// and never returned to the browser.

export type CalendarFeedResult =
  | { ok: true; token: string }
  | { ok: false; error: string };

export async function rotateCalendarFeedTokenAction(): Promise<CalendarFeedResult> {
  const { practitioner, studio } = await getCurrentPractitionerWithStudio();
  if (!practitioner.active) {
    return { ok: false, error: "Inactive practitioners cannot manage feeds." };
  }
  const supabase = await createClient();
  const token = generateCalendarFeedToken();
  const tokenHash = hashCalendarFeedToken(token);
  // Migration 0116: hash-only at rest, and 0178 keeps it that way — the raw
  // token is generated by this trusted server with the existing CSPRNG,
  // returned once below, and never crosses into the database.
  const { data: rotatedId, error } = await supabase.rpc(
    "set_own_calendar_feed_token_hash",
    { p_studio_id: studio.id, p_token_hash: tokenHash },
  );
  // `error` is a transport/permission failure; a NULL id means the command ran
  // and found no ACTIVE membership in that studio. Neither may report success.
  if (error || !rotatedId) {
    return {
      ok: false,
      error: "Could not generate a new calendar feed URL. Try again.",
    };
  }
  revalidatePath("/settings/profile");
  return { ok: true, token };
}

export async function clearCalendarFeedTokenAction(): Promise<CalendarFeedResult> {
  const { practitioner, studio } = await getCurrentPractitionerWithStudio();
  if (!practitioner.active) {
    return { ok: false, error: "Inactive practitioners cannot manage feeds." };
  }
  const supabase = await createClient();
  // Migration 0116: hash-only at rest — clearing the hash revokes the feed.
  // NULL is a VALUE here, not "unchanged": revocation is a real operation.
  const { data: clearedId, error } = await supabase.rpc(
    "set_own_calendar_feed_token_hash",
    { p_studio_id: studio.id, p_token_hash: null },
  );
  if (error || !clearedId) {
    return {
      ok: false,
      error: "Could not disable the calendar feed. Try again.",
    };
  }
  revalidatePath("/settings/profile");
  return { ok: true, token: "" };
}
